Europena_Website-v1/europena/europena/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^expertpage/', include('expertpage.urls')),
    url(r'^evaluation/', include('evaluation.urls')),
    url(r'^admin/', admin.site.urls),
]

Europena_Website-v1/europena/evaluation/urls.py
from django.conf.urls import url

from . import views

app_name = 'evaluation'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

Europena_Website-v1/europena/expertpage/urls.py
from django.conf.urls import url

from . import views

app_name = 'expertpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^(?P<document_id>[0-9]+[\/\]+[A-za-z0-9]+)/$', views.increase, name='increase'),
    url(r'^(?P<document_id>[0-9]+[\/\]+[A-za-z0-9]+)/(?P<value>[+-]?[0-9])/$', views.eval, name='eval'),
]

Europena_Website-v1/europena/evaluation/models.py
# Create your models here.

Europena_Website-v1/europena/expertpage/models.py
from django.db import models


class Document(models.Model):
    id = models.CharField(max_length=150, primary_key=True)
    contributor = models.CharField(max_length=500, null=True)
    country = models.CharField(max_length=30, null=True)
    created = models.CharField(max_length=50, null=True)
    creator = models.CharField(max_length=100, null=True)
    dataProvider = models.CharField(max_length=50, null=True)
    date = models.CharField(max_length=20, null=True)
    description = models.CharField(max_length=3000, null=True)
    format = models.CharField(max_length=20, null=True)
    identifier = models.CharField(max_length=100, null=True)
    language = models.CharField(max_length=10, null=True)
    medium = models.CharField(max_length=100, null=True)
    provider = models.CharField(max_length=100, null=True)
    publisher = models.CharField(max_length=100, null=True)
    relation = models.CharField(max_length=500, null=True)
    spatial = models.CharField(max_length=100, null=True)
    subject = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=1000, null=True)
    type = models.CharField(max_length=100, null=True)
    year = models.CharField(max_length=100, null=True)
    known_genre = models.CharField(max_length=20, null=True)
    approved = models.IntegerField(null=True)

    def __str__(self):
        return self.id + ' : ' + self.title

Europena_Website-v1/europena/evaluation/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'evaluation/index.html')

Europena_Website-v1/europena/expertpage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .models import Document


def index(request):
    all_documents = Document.objects.all()
    context = {'all_documents': all_documents}
    return render(request, 'expertpage/index.html', context)


def increase(request, document_id):
    all_documents = Document.objects.all()
    context = {'all_documents': all_documents}

    document_id = '/' + document_id;
    doc = get_object_or_404(Document, pk=str(document_id))

    doc.approved += 1
    doc.save()

    return render(request, 'expertpage/index.html', context)


def eval(request, document_id, value):
    all_documents = Document.objects.all()
    context = {'all_documents': all_documents}

    document_id = '/' + document_id;
    doc = get_object_or_404(Document, pk=str(document_id))

    doc.approved += int(value)
    doc.save()

    return HttpResponseRedirect('/expertpage')

Europena_Website-v1/europena/evaluation/templates/evaluation/index.html
{% extends 'base.html' %}

{% block body %}

<h1>TBD</h1>

{% endblock %}

Europena_Website-v1/europena/expertpage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Europena {% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'expertpage/style.css' %}">

    <!-- Paging -->
    <script src="https://code.jquery.com/jquery-2.2.0.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'expertpage:index' %}">
                Europena
            </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class={% block albums_active %} {% endblock %}>
                    <a href="{% url 'expertpage:index' %}">
                        <span class="glyphicon glyphicon-play" aria-hidden="true"></span> &nbsp;
                        Expert
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'evaluation:index' %}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span> &nbsp;
                        Evaluation
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Europena_Website-v1/europena/expertpage/templates/expertpage/index.html
{% extends 'base.html' %}

{% block body %}
{% if all_documents %}

<div class="container-fluid" id="player_container">

    <div class="row-fluid">
        <div class="col-lg-6">
            <audio controls id="audioPlayer"
                   src="http://127.0.0.1:9999/2059207/data_sounds_T214_25">
                Not supported format!
            </audio>
            <div class="jumbotron" id="genre_field">
                <b>I think the genre is: <var id="genre"> - </var></b>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="btn-group" role="group" id="thumbs-buttons">

                <form id="ok_form" onSubmit="return yes();" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-success" name="ok" value="OK">
                </form>
                <form id="nok_form" onSubmit="return no();" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" name="not_ok" value="Not OK">
                </form>


                <!--form id="ok_form" class="form-group" onSubmit="return test();" method="post">
                       {% csrf_token %}
                       <input type="submit" class="btn btn-success" name="ok" value="OK">
                       <input type="submit" class="btn btn-danger" name="not_ok" value="Not OK">
                </form-->
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <div class="col-fluid">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div><h3>Metadata</h3></div>
                </div>
                <div class="panel-body">
                    <br>
                    <b>ID:</b> <var id="song_id"></var> <br>
                    <b>Title:</b> <var id="song_title"></var> <br>
                    <b>Creator:</b> <var id="song_creator"></var><br>
                    <b>Description:</b> <var id="song_description"></var><br>
                    <b>Country:</b> <var id="song_country"></var><br>
                    <b>Spatial:</b> <var id="song_spatial"></var><br>
                    <b>Genre:</b> <var id="song_genre"></var><br>
                    <b>Approved:</b> <var id="song_approved"></var>
                </div>
            </div>
        </div>
    </div>

</div>


<!-- musictable -->
<div class="container-fluid" id="playlist_container">

    <table id="musictable" class="display-inverse" width="100%" cellspacing="0">
        <!-- Table Head -->
        <thead class="thead">
        <tr>
            <th>Play</th>
            <th>Title</th>
            <th>Id</th>
            <th>Creator</th>
            <th>Genre</th>
            <th>Description</th>
            <th>Country</th>
            <th>Spatial</th>
            <th>Approved</th>
        </tr>
        </thead>

        <tbody>
        {% for document in all_documents %}
        <tr>
            <th>
                <li><a href="http://127.0.0.1:9999{{ document.id }}.mp3"><span
                        class="glyphicon glyphicon-play"></span></a>
                </li>
            </th>
            <th> {{ document.title }}</th>
            <th> {{ document.id }}</th>
            <th> {{ document.creator }}</th>
            <th> {{ document.known_genre }}</th>
            <th> {{ document.description }}</th>
            <th> {{ document.country }}</th>
            <th> {{ document.spatial }}</th>
            <th> {{ document.approved }}</th>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{% else %}
<h3>There is no data</h3>
{% endif %}

<script class="init" type="text/javascript">
audioPlayer();
  function audioPlayer(){
    $("#audioPlayer")[0].src = $("#musictable li a")[8];

    $("#musictable li a").click(function(e){
	  e.preventDefault();
	  $("#audioPlayer")[0].src = this;
	  $("#audioPlayer")[0].play();
	});
  }




</script>


<script class="init" type="text/javascript">
var active_song_id

$(document).ready(function() {
   $('#musictable').DataTable( {
     "pagingType": "full_numbers",
     "columnDefs": [
            {
                "targets": [ 2 ],
                "visible": true,
                "searchable": true
            },
            {
                "targets": [ 5 ],
                "visible": false,
                "searchable": true
            },
            {
                "targets": [ 6 ],
                "visible": false,
                "searchable": true
            },
            {
                "targets": [ 7 ],
                "visible": false,
                "searchable": true
            }
     ]
   } );

   var table = $('#musictable').DataTable();
    $('#musictable tbody').on('click', 'tr', function () {
        var data = table.row( this ).data();
        $("#song_genre").text(data[4]);
        $("#genre").text(data[4]);
        active_song_id = data[2];
        $("#song_id").text(data[2]);
        $("#song_title").text(data[1]);
        $("#song_creator").text(data[3]);
        $("#song_description").text(data[5]);
        $("#song_country").text(data[6]);
        $("#song_spatial").text(data[7]);
        $("#song_approved").text(data[8]);
    } );
} );

function eval(content){
  //alert(content);
  if (content > 0) {
    link = document.URL + active_song_id.substring(1) + '/1';
    document.getElementById('ok_form').action = link;
  } else {
      link = document.URL + active_song_id.substring(1) + '/-1';
      document.getElementById('ok_form').action = link;
    }

}

function test(){
  link = document.URL + active_song_id.substring(1)+'/';
  document.getElementById('ok_form').action = link;
}


function yes(){
  link = document.URL + active_song_id.substring(1) + '/1' + '/';
  document.getElementById('ok_form').action = link;
}
function no(){
  link = document.URL + active_song_id.substring(1) + '/-1' + '/';
  document.getElementById('nok_form').action = link;
}



</script>

{% endblock %}